AcornSat.Visualiser/Pages/Index.razor, README.md
- Move the map toggle button to right-size when map collapsed.
- Change to different map provider
=> Move the map toggle button to right-size when map collapsed.

AcornSat.Visualiser/Pages/Enso.razor, AcornSat.Visualiser/Pages/Index.razor
It doesn't look right when you load in full-sized window. Everything else works!!!
=> Improve chart resizing

AcornSat.Visualiser/Pages/Index.razor, AcornSat.Visualiser/Shared/Collapsible.razor, AcornSat.Visualiser/Shared/Collapsible.razor.css, AcornSat.Visualiser/Shared/LocationInfo.razor, AcornSat.Visualiser/Shared/LocationInfo.razor.css, AcornSat.Visualiser/Shared/SuggestedCharts.razor
- Move the change location button to the location info section
- Days of extremes >> 20-year smoothing
=> Move the change location button to the location info section

ClimateExplorer.Core/Model/DataSetExtensionMethods.cs, ClimateExplorer.Visualiser/Pages/Index.razor, ClimateExplorer.Visualiser/Pages/Index.razor.cs, ClimateExplorer.Visualiser/Shared/DualRangeSlider.razor, ClimateExplorer.Visualiser/Shared/DualRangeSlider.razor.cs, ClimateExplorer.Visualiser/Shared/DualRangeSlider.razor.css, ClimateExplorer.Visualiser/Shared/Filter.razor, ClimateExplorer.Visualiser/Shared/SuggestedCharts.razor
Range slider control to easily limit the years for the graph
=> Range slider control to easily limit the years for the graph

ClimateExplorer.Core/Enums.cs, ClimateExplorer.Visualiser/ClimateExplorer.Visualiser.csproj, ClimateExplorer.Visualiser/Pages/Enso.razor, ClimateExplorer.Visualiser/Pages/Index.razor.cs, ClimateExplorer.Visualiser/Shared/ChartSeriesView.razor, ClimateExplorer.Visualiser/Shared/DataSetBrowser.razor, ClimateExplorer.Visualiser/Shared/DualRangeSlider.razor, ClimateExplorer.Visualiser/Shared/SuggestedCharts.razor, ClimateExplorer.Visualiser/UiLogic/ChartLogic.cs, ClimateExplorer.WebApi/MetaData/DataSetDefinitions.json
- Revert all references to inverted SOI (can just negate in the UI now)
=> Add range slider values for min and max

ClimateExplorer.Visualiser/Pages/Index.razor.cs, ClimateExplorer.Visualiser/wwwroot/index.html
- Issues as casing on the x scale (caused by the change to ExpandoObject)
- Updated chart.js
=> Fix trendline bug.

ClimateExplorer.Visualiser/Pages/Index.razor, ClimateExplorer.Visualiser/Pages/Index.razor.cs, ClimateExplorer.Visualiser/wwwroot/index.html
=> Clear filter

ClimateExplorer.Visualiser/Shared/DataSetBrowser.razor, ClimateExplorer.Visualiser/Shared/SuggestedCharts.razor
=> Preset cleanup + naming for "sea ice extent"

ClimateExplorer.Visualiser/Pages/Index.razor.cs, ClimateExplorer.Visualiser/UiLogic/ChartLogic.cs
=> Improve graph on mobile

ClimateExplorer.Visualiser/Pages/Index.razor.cs
=> Short title if mobile

ClimateExplorer.Visualiser/Shared/Collapsible.razor.css, ClimateExplorer.Visualiser/wwwroot/css/app.css
=> Only have the box-shadow and padding on desktop

ClimateExplorer.Visualiser/Shared/MapContainer.razor
=> Make map dragable, on mobile, when it's expanded

ClimateExplorer.Visualiser/Pages/Index.razor.cs, ClimateExplorer.Visualiser/Shared/WarmingStripe.razor.cs, ClimateExplorer.Visualiser/wwwroot/index.html
=> JavaScript hack to stop NavigateTo from scrolling to the top of the page

ClimateExplorer.Visualiser/Pages/Index.razor.cs
=> Fix HandleOnYearFilterChange

ClimateExplorer.Core/DataPreparation/Enums/SeriesDefinitionTypes.cs, ClimateExplorer.Core/DataPreparation/SeriesProvider.cs, ClimateExplorer.Visualiser/Pages/Index.razor.cs, ClimateExplorer.Visualiser/Services/Exporter.cs, ClimateExplorer.Visualiser/Shared/DataSetBrowser.razor, ClimateExplorer.Visualiser/UiModel/ChartSeriesDefinition.cs
To support average of temp max and min
Closes #91
=> Average of multiple series

ClimateExplorer.Visualiser/Pages/Index.razor.cs, ClimateExplorer.Visualiser/Shared/SuggestedCharts.razor
Also removed some superfluous characters in the chart title
=> Make the y-axis colours follow the first dataset colour.

ClimateExplorer.Visualiser/ClimateExplorer.Visualiser.csproj
=> Update third-party components

ClimateExplorer.Visualiser/Shared/LocationInfo.razor
=> Clear previous location's climate values

ClimateExplorer.Analyser/StaticContent/index-template.html, ClimateExplorer.Visualiser/ClimateExplorer.Visualiser.csproj, ClimateExplorer.Visualiser/Pages/ChartablePage.cs, ClimateExplorer.Visualiser/Pages/Index.razor, ClimateExplorer.Visualiser/Shared/ChartView.razor, ClimateExplorer.Visualiser/Shared/ChartView.razor.cs, ClimateExplorer.Visualiser/Shared/LocationInfo.razor, ClimateExplorer.Visualiser/Shared/SuggestedCharts.razor, ClimateExplorer.Visualiser/Shared/WarmestYears.razor, ClimateExplorer.Visualiser/Shared/WarmingStripe.razor, ClimateExplorer.Visualiser/wwwroot/index.html
=> Replace spinner with loading indicator and improve loading and layout

ClimateExplorer.Visualiser/Shared/LocationComponents/ChangeLocation.razor
=> Autocomplete menu hieght needs to be bigger

ClimateExplorer.Core/Model/Location.cs, ClimateExplorer.Visualiser/Shared/LocationComponents/ChangeLocation.razor
=> Selection location as a table and improve change location performance

ClimateExplorer.Visualiser/ClimateExplorer.Visualiser.csproj
=> Fix autocomplete

ClimateExplorer.Visualiser.UiTests/BrowserLocationTests.cs, ClimateExplorer.Visualiser.UiTests/ChartTests.cs, ClimateExplorer.Visualiser.UiTests/ClimateExplorer.Visualiser.UiTests.csproj, ClimateExplorer.Visualiser.UiTests/TestBase.cs, ClimateExplorer.Visualiser/Shared/ChartSeriesListView.razor, ClimateExplorer.Visualiser/Shared/ChartView.razor
=> Fix remove chart (includes UI test)

ClimateExplorer.Core/Model/Location.cs, ClimateExplorer.UnitTests/HeatingScoreTests.cs, ClimateExplorer.Visualiser/Shared/LocationComponents/LocationInfo.razor, ClimateExplorer.WebApi/Program.cs, ClimateExplorer.WebApi/cache/70a9af82-dd6f-41f4-af5f-b9701014bfeb.json
=> Calculate heating score from sets of 10 percentiles

ClimateExplorer.Visualiser/Shared/Collapsible.razor, ClimateExplorer.Visualiser/Shared/Collapsible.razor.css, ClimateExplorer.Visualiser/Shared/LocationComponents/LocationInfo.razor.css
=> Fix for mobile

ClimateExplorer.Core/Coordinates.cs, ClimateExplorer.Visualiser/Shared/Collapsible.razor.css, ClimateExplorer.Visualiser/Shared/LocationComponents/DriestYears.razor, ClimateExplorer.Visualiser/Shared/LocationComponents/LocationInfo.razor, ClimateExplorer.Visualiser/Shared/LocationComponents/WarmestYears.razor, ClimateExplorer.Visualiser/Shared/OverviewField.razor, ClimateExplorer.Visualiser/Shared/OverviewField.razor.css
=> Improve the location section styling

ClimateExplorer.Core/Model/Location.cs, ClimateExplorer.Core/Model/StationDistance.cs, ClimateExplorer.Data.Ghcnm/Program.cs, ClimateExplorer.Data.IntegratedSurfaceData/CountryFileProcessor.cs, ClimateExplorer.Visualiser/Shared/ChartView.razor.cs, ClimateExplorer.Visualiser/UiLogic/ChartSeriesListSerializer.cs, ClimateExplorer.Visualiser/UiModel/SeriesWithData.cs, ClimateExplorer.Visualiser/UiModel/SuggestedPresetLists.cs
=> Temp + co2, aggregation options on chart, fixes

ClimateExplorer.Visualiser/ClimateExplorer.Visualiser.csproj
=> Snackbar fix

ClimateExplorer.Visualiser/ClimateExplorer.Visualiser.csproj
=> Drop back to 7 for UI while we figure out what's wrong 

ClimateExplorer.Visualiser/UiLogic/ChartSeriesListSerializer.cs
=> Properly cope with data-types when changing locations

ClimateExplorer.WebApi/Program.cs
This reverts commit 374fd2e3d460d1bf195c7d0481c07464c1f4b32f.
=> Revert "Try AllowAnyMethod to resolve CORS error"

ClimateExplorer.Core/Calculators/IndexCalculator.cs, ClimateExplorer.Web.Client/Shared/LocationComponents/LocationInfo.razor, ClimateExplorer.WebApi/Program.cs
=> Rename index to anomaly

ClimateExplorer.Web/App.razor
should fix find location via name
=> Move current device script towards bottom of body

ClimateExplorer.Web.Client/UiModel/SuggestedPresetLists.cs
Sunspots are a proxy and has a much longer record.
=> Remove solar radiation preset.

ClimateExplorer.Web.Client/ClimateExplorer.Web.Client.csproj, ClimateExplorer.Web/ClimateExplorer.Web.csproj
This reverts commit e502729be0f85b791262368e2f7b37bb22e7fe0f.
=> Revert "NuGet package updates"

ClimateExplorer.Web.Client/UiModel/SuggestedPresetLists.cs
=> Move "Atmospheric CO₂ vs emissions" under other GHGs menu

ClimateExplorer.Web.Client/Pages/ChartablePage.cs, ClimateExplorer.Web.Client/Shared/ChartView.razor.cs, ClimateExplorer.Web.Client/UiLogic/ChartLogic.cs, ClimateExplorer.Web.Client/UiModel/SuggestedChartPresetModel.cs, ClimateExplorer.Web.Client/UiModel/SuggestedPresetLists.cs
- UpdateUiStateBasedOnQueryString for the year filtering.
- Add end year
=> Add start year to the address and some presets

ClimateExplorer.Web.Client/Pages/ChartablePage.cs
=> Prevent query data from being removed when there is no uri

ClimateExplorer.Core/DataSetDefinitionsBuilder.cs, ClimateExplorer.Web.Client/Pages/ChartablePage.cs, ClimateExplorer.Web.Client/Shared/ChartSeriesView.razor, ClimateExplorer.Web.Client/Shared/ChartSeriesView.razor.css, ClimateExplorer.Web.Client/Shared/ChartView.razor.cs, ClimateExplorer.Web.Client/UiModel/SuggestedPresetLists.cs
=> Add "Remove this series" to the series title bar

.github/workflows/master_api-climateexplorer.yml, .github/workflows/master_web-climateexplorer.yml, ClimateExplorer.AcornSatTransferFunctionAnalysis/ClimateExplorer.AcornSatTransferFunctionAnalysis.csproj, ClimateExplorer.CachingTool/ClimateExplorer.CachingTool.csproj, ClimateExplorer.Core/ClimateExplorer.Core.csproj, ClimateExplorer.Data.Bom.CreateTempMean/ClimateExplorer.Data.Bom.CreateTempMean.csproj, ClimateExplorer.Data.Bom/ClimateExplorer.Data.Bom.csproj, ClimateExplorer.Data.Ghcnd/ClimateExplorer.Data.Ghcnd.csproj, ClimateExplorer.Data.Ghcnm.Precipitation/ClimateExplorer.Data.Ghcnm.Precipitation.csproj, ClimateExplorer.Data.Ghcnm/ClimateExplorer.Data.Ghcnm.csproj, ClimateExplorer.Data.IntegratedSurfaceData/ClimateExplorer.Data.IntegratedSurfaceData.csproj, ClimateExplorer.Data.Misc/ClimateExplorer.Data.Misc.csproj, ClimateExplorer.Data.Niwa/ClimateExplorer.Data.Niwa.csproj, ClimateExplorer.Data.NoaaGlobalTemp/ClimateExplorer.Data.NoaaGlobalTemp.csproj, ClimateExplorer.DataPipeline/ClimateExplorer.DataPipeline.csproj, ClimateExplorer.SourceData/ClimateExplorer.SourceData.csproj, ClimateExplorer.UnitTests/ClimateExplorer.UnitTests.csproj, ClimateExplorer.Web.Client/ClimateExplorer.Web.Client.csproj, ClimateExplorer.Web.UiTests/ClimateExplorer.Web.UiTests.csproj, ClimateExplorer.Web/ClimateExplorer.Web.csproj, ClimateExplorer.Web/wwwroot/css/app.css, ClimateExplorer.WebApi/ClimateExplorer.WebApi.csproj, ClimateExplorer.WebApiClient/ClimateExplorer.WebApiClient.csproj, DPBlazorMapLibrary/DPBlazorMapLibrary.csproj, README.md
=> Update to .NET 9

ClimateExplorer.Core/DataPreparation/DataSetBuilder.cs, ClimateExplorer.Web.Client/Shared/LocationComponents/ClimateStripe.razor.cs, ClimateExplorer.Web.Client/Shared/LocationComponents/LocationInfo.razor
La Quiaca Observato should work now
=> Fixes for null data

ClimateExplorer.WebApi/cache-longterm/3e950837-5320-4312-a8e9-2d7fe7975bbe.json, ClimateExplorer.WebApi/cache-longterm/93d6f0e9-9cc9-4af1-b6fd-801b62f0bc41.json
=> Rebuild cache for elevation error
